image: python:3.11

stages:
  - build
  - deploy

before_script:
  - pip install mkdocs mkdocs-material

build_docs:
  stage: build
  script:
    - mkdocs build
  artifacts:
    paths:
      - site

pages:
  stage: deploy
  script:
    - mv site public
  artifacts:
    paths:
      - public
  only:
    - main